### ISSUE TITLE
Gem not selectable on MH when using identical weapons

### ISSUE THREAD

**Issue by koaschten** [cheald/shadowcraft-ui#50]
It seems like you can't select a gem to put into a prismatic socket if you equip identical weapons and only the MH has a socket. As soon as you add a socket to the offhand you can select a gem in the mainhand. The other way around, socket in offhand only works always.

e.g. http://shadowcraft.mmo-mumble.com/eu/ambossar/daemona currently wearing identical Demonblade Eviscerator just the MH having a socket.

![image](https://cloud.githubusercontent.com/assets/5974656/8965537/72c4cf3c-362c-11e5-9032-ad2e8d5edda3.png)

**Comment by WaveFunctionP** [comment]
Appears to only happen to weapons. Rings for instance, work just fine.

**Comment by timwoj** [comment]
This appears to have been fixed during the work for 7.0. Can you retest on the beta site?

**Comment by timwoj** [comment]
Scratch that, still broken. Steps to reproduce:

1. Equip two of the same weapon without sockets
2. Add a socket to the first weapon and add a gem to it. Note that the DPS doesn't change.
3. Add a socket to the second weapon and add a gem to it. Note that the DPS changes to account for both gems.

This is a hard problem to fix in that it will require rewriting a good portion of gear.coffee to change how we manage items. When a socket is added to an item, we modify the `item` object that we get from the database. This works fine for all of the other gear slots since there's only one of each item there. The code needs to be changed to modify the `gear` object for the slot and all of the subsequent display code used to display those items.

**Comment by timwoj** [comment]
This is no longer a problem because of artifacts.
